config/routes.rb
Website::Application.routes.draw do
  get "chapters/new"
  get "chapters/create"
  get "chapters/edit"
  get "chapters/update"
  get "chapters/destroy"
  root 'static_pages#home'

  resources :categories do
    resources :books do
      resources :chapters
    end
  end

  get 'static_pages/about', to: 'static_pages#about', as: 'about'
  get 'static_pages/art', to: 'static_pages#art', as: 'art'
  get 'static_pages/coding', to: 'static_pages#coding', as: 'coding'
  get 'static_pages/writing', to: 'static_pages#writing', as: 'writing'
  get 'bookshelf', to: 'categories#index', as: 'bookshelf'

end

app/models/book.rb
class Book < ActiveRecord::Base
	belongs_to :category
	has_many :chapters, dependent: :destroy
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :books, dependent: :destroy
end

app/models/chapter.rb
class Chapter < ActiveRecord::Base
	belongs_to :book
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
	def show
	  	@book = Book.find(params[:id])
		respond_to do |format|
			format.html
			format.js
    	end	
	end

	def create
		@category = Category.find(params[:category_id])
		@book = @category.books.build(book_params)
		@page = MetaInspector.new(@book.link, timeout: 10) #todo: check that we got a page
		@book.title = @page.title.strip
		@book.description = @page.description.strip
		respond_to do |format|
			if @book.save
	          format.html {redirect_to categories_path, notice: 'Book created.'}
	    		format.js
	    	else
	    		format.html{redirect_to categories_path, error: 'Error.'}
	    		format.js
	    	end
      	end
	end

	def edit
	  	@book = Book.find(params[:id])
		respond_to do |format|
		  	format.html
		  	format.js
	  	end
	end

	def update
		@book = Book.find(params[:id])
		respond_to do |format|
			if @book.update_attributes(book_edit_params)
				format.html {redirect_to categories_path, notice: 'Book edited.'}
				format.js
			else
				format.html {redirect_to categories_path, notice: 'Error.'}
				format.js
			end
		end
	end

	def destroy
	    @book = Book.find(params[:id])
	    respond_to do |format|
	    	if @book.destroy
	    		format.html {redirect_to categories_path, notice: 'Book deleted.'}
	    		format.js
	    	else
	    		format.html{redirect_to categories_path, notice: 'Error.'}
	    		format.js
	    	end
	    end
	end

	private

	def book_params
		params.require(:book).permit(:link)
	end

	def book_edit_params
		params.require(:book).permit(:title,:link,:description)
	end
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController

  def index
  	@categories = Category.all
  	@category = Category.new
    respond_to do |format|
      format.html
      format.js
    end
  end

  def edit
    @category = Category.find(params[:id])
    respond_to do |format|
        format.html
        format.js
      end
  end

  def update
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.update_attributes(category_params)
        format.html {redirect_to categories_path, notice: 'Category edited.'}
        format.js
      else
        format.html {redirect_to categories_path, notice: 'Error.'}
        format.js
      end
    end
  end

  def new
    @category = Category.new
    respond_to do |format|
      format.html {redirect_to @categories} #todo redirect to new page
      format.js
    end
  end

  def create
    @category = Category.new(category_params)
    respond_to do |format|
      if @category.save
        @categories = Category.all
        format.html {redirect_to @categories, notice: 'Category created.'}
        format.js
      else
        format.html {redirect_to @categories, notice: 'Error.'} #todo log error
        format.js
      end
    end
  end

  def destroy
    @categories = Category.all
    @category = Category.find(params[:id])
    respond_to do |format|
      if @category.destroy
        format.html {redirect_to categories_path, notice: 'Category deleted.'}
        format.js
      else
        format.html {redirect_to categories_path, notice: 'Error.'} #todo log error
        format.js
      end
    end
  end

	private

	def category_params
		params.require(:category).permit(:name)
	end
end

app/controllers/chapters_controller.rb
class ChaptersController < ApplicationController

	def new
		@book = Book.find(params[:book_id])
		respond_to do |format|
		  format.html {redirect_to categories_path}
		  format.js
		end
	end

	def create
		@book = Book.find(params[:book_id])
		@chapter = @book.chapters.build(chapter_params)
		if @chapter.isLink == true # if chapter type is a link
			@page = MetaInspector.new(@chapter.link, timeout: 10) #todo: check that we got a page
			@chapter.title = @page.title.strip
			@chapter.content = @page.description.strip
			# if chapter is not a link, then content would have been set by the form
		end
		respond_to do |format|
			if @chapter.save
	          format.html {redirect_to categories_path, notice: 'Chapter created.'}
	    		format.js
	    	else
	    		format.html{redirect_to categories_path, error: 'Error.'}
	    		format.js
	    	end
      	end
	end

	def edit
		@chapter = Chapter.find(params[:id])
		respond_to do |format|
		  	format.html
		  	format.js
	  	end
	end

	def update
		@chapter = Chapter.find(params[:id])
		respond_to do |format|
			if @chapter.update_attributes(chapter_params)
				format.html {redirect_to categories_path, notice: 'Chapter edited.'}
				format.js
			else
				format.html {redirect_to categories_path, notice: 'Error.'}
				format.js
			end
		end
	end

	def destroy
	    @chapter = Chapter.find(params[:id])
	    respond_to do |format|
	    	if @chapter.destroy
	    		format.html {redirect_to categories_path, notice: 'Chapter deleted.'}
	    		format.js
	    	else
	    		format.html{redirect_to categories_path, notice: 'Error.'}
	    		format.js
	    	end
	    end
	end

	private

	def chapter_params
		params.require(:chapter).permit(:content, :link, :isLink)
	end

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def about
  end

  def art
  end

  def coding
  end

  def writing
  end

  def bookshelf
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/books_helper.rb
module BooksHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/chapters_helper.rb
module ChaptersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/books/_book.html.erb
<div class="book" data-id="<%= book.id %>">

	<div class="tools">
		<%= link_to "<i class=\"glyphicon glyphicon-chevron-down\"></i>".html_safe, category_book_path(book.category, book), remote: true %>
		<%= link_to "<i class=\"glyphicon glyphicon-pencil\"></i>".html_safe, edit_category_book_path(book.category, book), remote: true %>
		<%= link_to "<i class=\"glyphicon glyphicon-remove\"></i>".html_safe, [book.category, book], remote: true, method: :delete, data: {confirm: "You sure?"} %> 
	</div>

	<div class="content">
		<%= link_to book.title, book.link %> </p>
		<p><%= simple_format(book.description) %></p>
	</div>

	<div class="editform" style="display:none"></div>
	
	<div class="chapterList" style="display:none"></div>

	<div class="formNewChapter" class:'display:none'></div>

</div>			

<div class="borderBetween center-block">
</div>

app/views/books/_bookChapters.html.erb
<div class="chapters">
	<% book.chapters.each do |chapter| %>
		<div class="chapter" data-id="<%= chapter.id %>">
			<%= render chapter, chapter: chapter %>	
		</div>
	<% end %>
</div>

<div class="addChapterLink">
	<%= link_to "Add Chapter", new_category_book_chapter_path(book.category, book), class: 'btn btn-default', remote: true %>
</div>

app/views/books/_chapterForm.html.erb
<%= form_for([book.category, book, book.chapters.build], remote: true,  ) do |f| %>
	<div class="form-group">
    	<%= f.text_area :content, class: 'form-control text_area' %> 
	</div>
    <%= f.submit "Save Chapter", class: 'submitButton btn btn-default'%>
<% end %>

app/views/books/_formBookFull.html.erb
<%= form_for [book.category, book], remote: true do |f| %>
	<ul class="errors"></ul>
	<div class="form-group">
	<%= f.label :title %>
	<%= f.text_field :title, class: 'form-control' %>
	</div>

	<div class="form-group">
	<p><%= f.label :description %><br>
	<%= f.text_area :description, rows: 10, class: 'form-control text_area' %></p>
	</div>

	<div class="form-group">
	<p><%= f.label :link %><br>
	<%= f.url_field :link, class: 'form-control' %></p>
	</div>

	<p><%= f.submit "Save", :class => 'submitButton btn btn-default'%></p>
<% end %>

app/views/books/create.js.erb
var $categorydiv = $('div.categorydiv[data-id="<%= @category.id %>"]');
var $category = $categorydiv.find('.categorybooks');
$category.append("<%= escape_javascript(render 'book', book: @book) %>");

app/views/books/destroy.js.erb
var $bookdiv = $('div.book[data-id="<%= @book.id %>"]');
$("#errors").html("");
<% if @book.errors.any? %>
  <% @book.errors.full_messages.each do |message| %>

   $("#errors").append($("<li />").html("<%= message.html_safe %>"))
  alert('error');
 <% end %>
<% else %>
	$bookdiv.remove();
<% end %>

app/views/books/edit.js.erb
var $bookdiv = $('div.book[data-id="<%= @book.id %>"]');
$bookdiv.find('.editform').html("<%= escape_javascript(render 'books/formBookFull', book: @book)%>");
$bookdiv.find('.editform').show();
$bookdiv.find('.content').hide();
$bookdiv.find('.chapters').hide();

app/views/books/show.js.erb
var $bookdiv = $('div.book[data-id="<%= @book.id %>"]');
$chaptersDiv = $bookdiv.find(".chapterList");
$chaptersDiv.html("<%= escape_javascript(render 'bookChapters', book: @book) %>");
$chaptersDiv.show(); // instead, in client-side I can call toggle show from the link. then server fills it with chapters.
$chevron = $bookdiv.find('.glyphicon-chevron-down');
$chevron.toggleClass = 'glyphicon-chevron-down glyphicon-chevron-up'; // this would also be client-side

app/views/books/update.js.erb
var $bookdiv = $('div.book[data-id="<%= @book.id %>"]');
$("#errors").html("")

<% if @book.errors.any? %>
	<% @book.errors.full_messages.each do |message| %>
		$("#errors").append($("<li />").html("<%= message.html_safe %>"))
	<% end %>
<% else %>
	$bookdiv.html("<%= escape_javascript(render 'book', book: @book) %>");
<% end %>

app/views/categories/_category.html.erb
<div class="categoryHeader">
	<%= render 'categoryTitle', category: category %>
</div>

<div class="shelf collapse in">
	<div class="borderTop center-block"></div>

	<div class="categorybooks">
		<% category.books.each do |book| %>
			<%= render book, book: book %>
		<% end %>
	</div>

	<div class="formNewBook">
		<%= render 'shared/formCategoryBook', category: category %>
	</div>

	<div class="borderBottom center-block "></div>
</div>

app/views/categories/_categoryTitle.html.erb
<div class="categoryTitle">
	<div class="tools">
		<%= link_to "<i class=\"glyphicon glyphicon-pencil\"></i>".html_safe, edit_category_path(category), remote: true%>
		<%= link_to "<i class=\"glyphicon glyphicon-remove\"></i>".html_safe, category, method: :delete, remote: true, data: {confirm: "You sure?"} %> 
	</div>

	<%= link_to category.name, {}, {name: category.id} %>

	<a data-toggle="collapse-next" data-target=".shelf" class="collapseButton">
	<i class="glyphicon glyphicon-chevron-down"></i>
	</a>
</div>

app/views/categories/_formCategoryBook.html.erb
<%= form_for([category, category.books.build], remote: true,  ) do |f| %>
    <%= f.url_field :link, class: 'book-input'%> <%= f.submit "Add", :class => 'submitButton btn btn-default'%>
<% end %>

app/views/categories/_formnewcategory.html.erb
		<%= form_for(category, remote: true) do |f| %>
		    <%= f.text_field :name %> <%= f.submit "Save", :class => 'submitButton btn btn-default'%>
		<% end %>

app/views/categories/_links.html.erb
<div id="bookshelfLinks">
	<ul>
		<% categories.each do |category| %>
			<li><%= link_to category.name, categories_path(anchor: category.id), class: 'scroll-link' %></li>
		<% end %>
	</ul>
</div>

app/views/categories/create.js.erb
$("#errors").html("");
<% if @category.errors.any? %>
  <% @category.errors.full_messages.each do |message| %>

   $("#errors").append($("<li />").html("<%= message.html_safe %>"))
  alert('error');
 <% end %>
<% else %>
  $("#category_list").html("<%= escape_javascript(render 'shared/list', categories: @categories) %>");

	$('#add_link').show();
	$('#add_category').hide();
<% end %>

app/views/categories/destroy.js.erb
var $category = $('div.categorydiv[data-id="<%= @category.id %>"]');
$category.remove();

app/views/categories/edit.js.erb
var $categorydiv = $('div.categorydiv[data-id="<%= @category.id %>"]');
var $categoryHeader = $categorydiv.find('.categoryHeader');

$categoryHeader.html("<%= escape_javascript(render 'formnewcategory', category: @category) %>")

app/views/categories/index.html.erb
<p>
	Here's where I keep the things other people have made that I think are worth keeping.
</p>

<ul id="errors"></ul>

<%= render 'shared/list', categories: @categories %>

<p id="add_link"><%= link_to 'Add a Category', new_category_path, remote: true, id: 'link_add_cat', class: 'btn btn-default'%></p>

<div id="add_category" style="display:none;">
</div>

<script>
$(document).ready(function(){
	$('#bookshelfSidebar').html("<%= escape_javascript(render 'links', categories: @categories) %>")
});

</script>

app/views/categories/new.js.erb
$("#add_category").html("<%= escape_javascript(render 'formnewcategory', category: @category) %>")
$("#add_link").hide();
$("#add_category").show();

app/views/categories/update.js.erb
var $categorydiv = $('div.categorydiv[data-id="<%= @category.id %>"]');
var $categoryHeader = $categorydiv.find('.categoryHeader');

$categoryHeader.html("<%= escape_javascript(render 'categoryTitle', category: @category) %>")

app/views/chapters/_chapter.html.erb
<div class="tools">
	<%= link_to "<i class=\"glyphicon glyphicon-pencil\"></i>".html_safe, edit_category_book_chapter_path(chapter.book.category, chapter.book, chapter), remote: true %>
	<%= link_to "<i class=\"glyphicon glyphicon-remove\"></i>".html_safe, [chapter.book.category, chapter.book, chapter], method: :delete, remote: true, data: {confirm: "You sure?"}  %>
</div>

<div class="title">
	<% if chapter.isLink? %>
		<%= link_to chapter.title, chapter.link %>
	<% end %>
</div>

<div class="content">
	<%= simple_format(chapter.content) %>
</div>

<div class="editform"></div>

app/views/chapters/_chapterForm.html.erb
<script>
$('input[type="radio"][data-behavior="toggle-type"]').click(function(evt) {	
	$formdiv = $(this).closest("div");
	$link = $formdiv.find(".linkContainer");
	$text = $formdiv.find(".textContainer");
	if ($(this).val() == "true"){
		$link.show();
		$text.hide();
	}
	else if ($(this).val() == "false"){
		$link.hide();
		$text.show();
	}
});
</script>

<%= form_for([book.category, book, chapter], remote: true ) do |f| %>

	<div class="form-group linkContainer">
    	<%= f.url_field :link, class: 'form-control' %> 
	</div>

	<div class="form-group textContainer" style="display:none">
    	<%= f.text_area :content, rows: 10, class: 'form-control text_area' %> 
	</div>
	<table>
		<tr>
			<td>
			    <%= f.radio_button :isLink, true, checked: 'checked', data: {behavior: "toggle-type"} %> 
			    <%= f.label :isLink, 'Link' %>

			    <%= f.radio_button :isLink, false, data: {behavior: "toggle-type" } %> 
			    <%= f.label :isLink, 'Text' %>
			</td>
			<td>
				<%= f.submit "Save Chapter", class: 'submitButton btn btn-default' %>
			</td>
		</tr>
	</table>
<% end %>

app/views/chapters/_updateChapterForm.html.erb
<%= form_for([chapter.book.category, chapter.book, chapter], remote: true ) do |f| %>
	<% if chapter.isLink == true %>
		<div class="form-group">
			<%= f.label :title %>
			<%= f.text_field :title, class: 'form-control' %>
		</div>
		<div class="form-group">
			<%= f.label :link %>
    		<%= f.url_field :link, class: 'form-control' %> 
    	</div>
	<% end %>

	<div class="form-group">	
    	<%= f.text_area :content, rows: 5, class: 'form-control text_area' %> 
	</div>

	<%= f.submit "Save Chapter", class: 'submitButton btn btn-default' %>
<% end %>

app/views/chapters/create.js.erb
var $bookdiv = $('div.book[data-id="<%= @book.id %>"]');
$formNewChapter = $bookdiv.find(".formNewChapter");
$chapters = $bookdiv.find(".chapters");
$formNewChapter.html("");
$formNewChapter.hide();
$chapters.append("<div class=\"chapter\"><%= escape_javascript(render 'chapter', chapter: @chapter) %></div>");
$bookdiv.find(".addChapterLink").show();
/*temporary fix*/
$bookdiv.find(".chapterList").html("<%= escape_javascript(render '/books/bookChapters', book: @book) %>");
/*temporary fix for bug--after create, edit.js.erb is breaking*/

app/views/chapters/destroy.js.erb
var $chapter = $('div.chapter[data-id="<%= @chapter.id %>"]');
$chapter.remove();

app/views/chapters/edit.js.erb
var $chapter = $('div.chapter[data-id="<%= @chapter.id %>"]');
$chapter.find('.editform').html("<%= escape_javascript(render 'updateChapterForm', chapter: @chapter)%>");
$chapter.find('.editform').show();
$chapter.find('.content').hide();
$chapter.find('.tools').hide();

app/views/chapters/new.js.erb
var $bookdiv = $('div.book[data-id="<%= @book.id %>"]');
$formNewChapter = $bookdiv.find(".formNewChapter");
$formNewChapter.html("<%= escape_javascript(render 'chapterForm', book: @book, chapter: @book.chapters.build) %>");
$formNewChapter.show();
$bookdiv.find(".addChapterLink").hide();

app/views/chapters/update.js.erb
var $chapter = $('div.chapter[data-id="<%= @chapter.id %>"]');
$chapter.html("<%= escape_javascript(render 'chapter', chapter: @chapter) %>");

app/views/layouts/_sidebar.html.erb
<div id="sidebar" data-spy="affix" data-offset-top="85" data-clampedwidth=".col-mid-3">
	<ul>
		<li><%= link_to "about", about_path %></li>
		<li><%= link_to "art", art_path %></li>
		<li>
		<%= link_to "coding", coding_path %></li>
		<li>
		<%= link_to "writing", writing_path %></li>
		<li>
		<%= link_to "bookshelf", bookshelf_path %>
		<div id="bookshelfSidebar" class="subSidebar"></div>
	</li>
	</ul>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<%= csrf_meta_tag %>
<head>
  <title>Website</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body data-spy="scroll" data-target="#bookshelfLinks">
<% flash.each do |name, msg| -%>
  <%= content_tag :div, msg, class: name %>
<% end -%>
<div class="container">
	<div class="row nopadding">
		<div class="col-md-6 col-md-offset-1 top">
			Rita Zevallos. <%= link_to "person", about_path %>/<%= link_to "artmaker", art_path %>/<%= link_to "coder", coding_path %>/<%= link_to "writer", writing_path %>/<%= link_to "collector", bookshelf_path %>
		</div>
	</div>
	<div class="row">
		<div class="col-md-2 sidebar-container">
			<%= render 'layouts/sidebar' %>
		</div>
		<div class="col-md-8" id="content" >
			<%= yield %>
		</div>
	</div>
	<div class="nopadding navbar-fixed-bottom footer">
		(All content and design by Rita Zevallos.)
	</div>
</div>

</body>
</html>

app/views/shared/_formCategoryBook.html.erb
<%= form_for([category, category.books.build], remote: true,  ) do |f| %>
    <%= f.url_field :link %> <%= f.submit "Add", :class => 'submitButton btn btn-default'%>
<% end %>

app/views/shared/_list.html.erb
<ul id="category_list">
<% categories.each do |category| %>

	<li><div class="categorydiv" data-id="<%= category.id %>">
		<%= render category, category: category %>
	</div></li>
	
<% end %>
</ul>

app/views/static_pages/about.html.erb
<h1>StaticPages#about</h1>
<p>Find me in app/views/static_pages/about.html.erb</p>

app/views/static_pages/bookshelf.html.erb
<p>
	Here's where I keep the things other people have made that I think are worth keeping.
</p>
<p>
	Implementation steps:
</p>
<p>
	1. No categories. It's just a list of links (no titles) that I can add to with the form at the bottom (but I have to refresh to see it). New things automatically get added at the end.<br />
	2. Make the form JSON so the added thing appears immediately.<br />
	3. Get the title of the website and store it.<br />
	4. Optionally add a description (text) that can include quotes or a summary.<br />
	5. Add categories. Categories can be collapsed.<br />
	6. Add a chrome app.<br />
	7. Show when a website has been updated.<br />
</p>
<p>
	Things to consider:
</p>
<p>
	I want to both have particular articles as well as blogs that I follow. How to do this?
</p>

app/views/static_pages/home.html.erb
<p>(Eventually here will be one of those rotating image things.)</p>
<%= image_tag('girl-and-plant.png', class: 'img-responsive') %>